"""Phase B19 -- minimal tangent credit module. Tests whether the exact
online-credit dimension for a temporal core R is controlled by the
two-sided tangent bimodule

    B = A P A,   A = span{I, R, R^2, ...} (algebra generated by R),
                 P = span of trainable temporal-parameter tangents
                     dR/dtheta_k (as r x r matrices),

rather than defaulting to r^2 (B18's dense-storage K-chain). Key
reframing found while building this: B18's K-chain used P = span{I}
(the SOURCE-injection tangent, generically commuting with R) and
stored it as a dense r x r matrix -- r^2 numbers -- even though the
theory here predicts the TRUE minimal dimension for a commuting
tangent is dim(A) <= r, not r^2. B18's r^2 was a measured SUFFICIENT
(storage) cost, never verified as MINIMAL. This phase verifies that
distinction directly, plus the separate (and generically much larger)
question of R's OWN trainable-entry tangents.

All dimension claims are verified two ways: (i) algebraically, via
rank-revealing SVD on explicit bases of A and B = APA; (ii) exact
sensitivity simulation (linear system, exact-by-linearity, matching
B16.2/B18's established style) compared against the reduced-dimension
"minimal online recursion" built directly from the measured basis of
B, to machine precision.

Run:  python -m credit_memory.b19_tangent_module
"""
from __future__ import annotations

import numpy as np


# ---------------------------------------------------------------------------
# Part A/B core: algebra + bimodule dimension via rank-revealing SVD
# ---------------------------------------------------------------------------
def matrix_powers(R, max_k=None):
    r = R.shape[0]
    max_k = r if max_k is None else max_k  # Cayley-Hamilton bounds degree <= r
    powers = [np.eye(r, dtype=R.dtype)]
    Rk = np.eye(r, dtype=R.dtype)
    for _ in range(1, max_k):
        Rk = Rk @ R
        powers.append(Rk)
    return powers


def subspace_basis(mats, tol=1e-9):
    """Rank-revealing SVD basis for span{mats} (each an r x r matrix),
    vectorized. Returns (orthonormal basis rows, singular values, rank)."""
    vecs = np.stack([M.ravel() for M in mats], axis=0)
    U, S, Vt = np.linalg.svd(vecs, full_matrices=False)
    if len(S) == 0 or S[0] < 1e-300:
        return Vt[:0], S, 0
    rank = int(np.sum(S > tol * S[0]))
    return Vt[:rank], S, rank


def algebra_basis(R, tol=1e-9):
    """A = span{I, R, R^2, ...}."""
    return subspace_basis(matrix_powers(R), tol=tol)


def bimodule_basis(R, E_list, tol=1e-9):
    """B = A P A = span{R^a E_i R^b : 0<=a,b<=r-1, E_i in P}."""
    r = R.shape[0]
    powers = matrix_powers(R)
    mats = []
    for E in E_list:
        for a in range(r):
            for b in range(r):
                mats.append(powers[a] @ E @ powers[b])
    return subspace_basis(mats, tol=tol)


def predicted_dims(R, E_list, tol=1e-9):
    _, Sa, dimA = algebra_basis(R, tol=tol)
    _, Sb, dimB = bimodule_basis(R, E_list, tol=tol)
    return dict(dim_A=dimA, dim_P=len(E_list), dim_APA=dimB, r=R.shape[0])


# ---------------------------------------------------------------------------
# Minimal online recursion built directly from a measured basis of B:
# since R*(R^a E R^b) = R^{a+1} E R^b stays in span{R^c E R^b} (closed
# under left-mult by R via Cayley-Hamilton reduction), B is a LEFT
# A-module -- multiplication by R acts on B via a d x d matrix R_B
# (d = dim B) in the measured basis. The minimal exact online credit
# recursion is then coords_t = R_B @ coords_{t-1} + inject(u_t), a
# genuinely d-dimensional (not r^2-dimensional) linear recursion.
# ---------------------------------------------------------------------------
def build_minimal_recursion(R, E_list, tol=1e-9):
    basis, S, d = bimodule_basis(R, E_list, tol=tol)  # d x r^2, orthonormal rows
    r = R.shape[0]
    if d == 0:
        return dict(d=0, basis=basis, R_B=np.zeros((0, 0)), inject=[])
    # R_B: express R @ M_j (for each basis vector M_j, reshaped to r x r) in
    # the same basis via least-squares (exact since R@B subset B).
    R_B = np.zeros((d, d))
    for j in range(d):
        Mj = basis[j].reshape(r, r)
        RMj = R @ Mj
        coords, *_ = np.linalg.lstsq(basis.T, RMj.ravel(), rcond=None)
        R_B[:, j] = coords
    # injection vectors: for each E_i, the "instantaneous" contribution E_i
    # itself, expressed in the basis (a=b=0 term of the generating set).
    inject = []
    for E in E_list:
        coords, *_ = np.linalg.lstsq(basis.T, E.ravel(), rcond=None)
        inject.append(coords)
    return dict(d=d, basis=basis, R_B=R_B, inject=inject)


def verify_minimal_recursion(R, E_list, T_=30, n_sources=6, seed=0, tol=1e-9):
    """Exact verification: true full-matrix K_t (=sum u_t^i R^{t-tau} E_i,
    literal (r,r) simulation) vs. the reduced d-dim recursion built from
    the measured basis of B, projected back to (r,r) for comparison."""
    rng = np.random.RandomState(seed)
    r = R.shape[0]
    rec = build_minimal_recursion(R, E_list, tol=tol)
    d = rec["d"]
    max_err = 0.0
    for _ in range(n_sources):
        u = rng.randn(T_, len(E_list))
        K_true = np.zeros((r, r))
        coords = np.zeros(d)
        for t in range(T_):
            K_true = R @ K_true
            for i, E in enumerate(E_list):
                K_true = K_true + u[t, i] * E
            if d > 0:
                coords = rec["R_B"] @ coords
                for i in range(len(E_list)):
                    coords = coords + u[t, i] * rec["inject"][i]
                K_pred = (coords @ rec["basis"]).reshape(r, r)
            else:
                K_pred = np.zeros((r, r))
            err = float(np.max(np.abs(K_true - K_pred)))
            max_err = max(max_err, err)
    return max_err, d


# ---------------------------------------------------------------------------
# Architecture constructors (Part A)
# ---------------------------------------------------------------------------
def arch_dense(r, rng):
    R = rng.randn(r, r) / np.sqrt(r) * 0.9
    E_list = [np.eye(r)[i:i + 1, :].T @ np.eye(r)[j:j + 1, :]
             for i in range(r) for j in range(r)]
    return R, E_list


def arch_commuting_diag(r, rng):
    U = rng.randn(r, r)
    lam = np.linspace(0.5, 0.9, r)
    Uinv = np.linalg.inv(U)
    R = U @ np.diag(lam) @ Uinv
    E_list = [U @ np.diag((np.arange(r) == j).astype(float)) @ Uinv for j in range(r)]
    return R, E_list


def arch_polynomial(r, p, rng):
    """R(theta) = sum_{k=0}^{p-1} theta_k R0^k, fixed stable R0."""
    R0 = arch_commuting_diag(r, rng)[0]
    powers = matrix_powers(R0, max_k=p)
    theta0 = rng.uniform(0.1, 0.3, p)
    R = sum(theta0[k] * powers[k] for k in range(p))
    return R, powers  # E_list = the powers themselves


def arch_block(r_blocks, rng):
    """Several independent blocks (dense, commuting each) -- overall R is
    block-diagonal; overall P is the union of each block's own tangents,
    embedded (zero-padded) into the full space."""
    total_r = sum(r_blocks)
    R = np.zeros((total_r, total_r))
    E_list = []
    off = 0
    for rb in r_blocks:
        Rb, Eb = arch_dense(rb, rng)
        R[off:off + rb, off:off + rb] = Rb
        for E in Eb:
            Efull = np.zeros((total_r, total_r))
            Efull[off:off + rb, off:off + rb] = E
            E_list.append(Efull)
        off += rb
    return R, E_list


def arch_single_tangent(r, rng, kind="generic"):
    R0 = arch_commuting_diag(r, rng)[0]
    if kind == "generic":
        E = rng.randn(r, r)
    elif kind == "commuting":
        E = np.diag(rng.randn(r))  # commutes with R0's diagonal structure... (see note)
    elif kind == "zero_diag":
        E = rng.randn(r, r)
        np.fill_diagonal(E, 0.0)
    elif kind == "low_rank":
        u = rng.randn(r, 1); v = rng.randn(1, r)
        E = u @ v
    else:
        raise ValueError(kind)
    return R0, [E]


# ---------------------------------------------------------------------------
# Part C: source/query quotient. Even a large A P A can overcount if the
# specific source v / query c don't have "generic" support -- measure the
# REACHABLE+OBSERVABLE dimension for a given (v, c): rank of the r x r
# "Hankel" H[a,b] = c^T R^a E_i R^b v, stacked over tangents i.
# ---------------------------------------------------------------------------
def source_query_quotient_dim(R, E_list, v, c, tol=1e-9):
    r = R.shape[0]
    powers = matrix_powers(R)
    rows = []
    for E in E_list:
        H = np.zeros((r, r))
        for a in range(r):
            for b in range(r):
                H[a, b] = float(c @ (powers[a] @ E @ powers[b]) @ v)
        rows.append(H.ravel())
    M = np.stack(rows, axis=0)
    _, S, Vt = np.linalg.svd(M, full_matrices=False)
    rank = int(np.sum(S > tol * S[0])) if len(S) and S[0] > 0 else 0
    return rank


# ---------------------------------------------------------------------------
# Part F: symmetry-breaking test. A0 = I_n (x) R (protected module: the
# per-copy K-chain, r x r shared across copies). Perturb A = A0 +
# sigma*Delta, Delta a GENERIC coupling matrix (not block-diagonal --
# genuinely mixes different copies' states). Measure the gradient
# reconstruction error incurred by using the UNPERTURBED module's exact
# K-chain formula (computed as if A0 were the true dynamics) against the
# TRUE (perturbed) system's sensitivity trajectory, as a function of
# sigma and horizon T, for normal vs nonnormal R.
# ---------------------------------------------------------------------------
def symmetry_breaking_error(R, n, sigma, T_, seed=0):
    """Returns the relative error of the protected-module (A0) prediction
    against the TRUE (A0+sigma*Delta) sensitivity trajectory, for a
    single source column entering copy 0 only (so the unperturbed answer
    is the plain r-dim K-chain applied to that copy)."""
    rng = np.random.RandomState(seed)
    r = R.shape[0]
    N_ = n * r
    A0 = np.kron(np.eye(n), R)
    Delta = rng.randn(N_, N_)
    Delta = Delta / np.linalg.norm(Delta, 2)
    A = A0 + sigma * Delta

    u = rng.randn(T_)
    b = np.zeros(N_); b[0] = 1.0  # source enters copy 0's first coordinate

    # true (perturbed) trajectory
    K_true = np.zeros(N_)
    true_traj = np.zeros((T_, N_))
    for t in range(T_):
        K_true = A @ K_true + u[t] * b
        true_traj[t] = K_true

    # protected-module prediction: use A0 (unperturbed) dynamics
    K_pred = np.zeros(N_)
    pred_traj = np.zeros((T_, N_))
    for t in range(T_):
        K_pred = A0 @ K_pred + u[t] * b
        pred_traj[t] = K_pred

    err = np.linalg.norm(true_traj - pred_traj) / (np.linalg.norm(true_traj) + 1e-30)
    return dict(rel_err=float(err), sigma=sigma, T=T_, T_sigma=T_ * sigma)


# ---------------------------------------------------------------------------
# Part D: forward expressivity of O(r)-credit (constrained-tangent) cores
# vs the r^2-credit dense core, at MATCHED r/N/depth/training budget.
# Reuses b18_temporal_core's forward/bptt_gradients (which always compute a
# FULL dense r x r gradient dR) but PROJECTS that gradient onto a fixed
# tangent basis {E_k} before the Adam update, and reconstructs
# R = R_fixed + sum theta_k E_k after each step -- so R is genuinely
# constrained to move only within the architecture's own tangent space
# throughout training, not just at init (the B18 R_FAMILIES only fixed
# structure at INIT; gradients there were always full-rank r^2).
# ---------------------------------------------------------------------------
def train_constrained(layer_specs_with_tangents, M_IN0, task_fn, task_arg, seed,
                      steps=600, T_task=60, batch_task=8, lr=1e-3):
    """layer_specs_with_tangents: list of dicts each with 'width','r',
    'R_fixed' (r x r ndarray), 'E_list' (list of r x r ndarrays, the
    trainable tangent basis), 'routing'."""
    import credit_memory.b18_temporal_core as b18

    rng = np.random.RandomState(seed)
    layers, Bs, thetas = [], [], []
    M_in = M_IN0
    for l_idx, spec in enumerate(layer_specs_with_tangents):
        r = spec["r"]; width = spec["width"]
        R_fixed = spec["R_fixed"]; E_list = spec["E_list"]
        theta0 = np.zeros(len(E_list))
        R0 = R_fixed + sum(theta0[k] * E_list[k] for k in range(len(E_list))) \
            if E_list else R_fixed
        layer = b18.Layer(width, r, R0.copy(), trainable_R=True,
                          routing=spec.get("routing", "dense"), M_IN=M_in)
        layers.append(layer)
        routing_scale = 1.0 if l_idx == 0 else 0.3
        Bs.append(b18.init_routing(layer, M_in, rng, scale=routing_scale))
        thetas.append(theta0)
        M_in = width
    c = rng.randn(layers[-1].width) / np.sqrt(layers[-1].width)
    params = dict(layers=layers, Bs=Bs, c=c)

    flat = b18.flatten_params(params)
    m_ = np.zeros_like(flat); v_ = np.zeros_like(flat)
    losses = []
    rng2 = np.random.RandomState(4000 + seed)
    for step in range(1, steps + 1):
        x, y = task_fn(rng2, T_task, batch_task, M_IN0, task_arg)
        if x.ndim == 2:
            x = x[:, :, None]
        h_all, yhat = b18.forward(params, x)
        loss = 0.5 * float(np.mean((yhat - y) ** 2))
        grads = b18.bptt_gradients(params, x, y, h_all)

        # project each layer's full dense dR onto its own tangent basis,
        # zero out the rest, so the Adam step only moves within span{E_k}
        for l_idx, spec in enumerate(layer_specs_with_tangents):
            E_list = spec["E_list"]
            if not E_list:
                grads["dR"][l_idx][:] = 0.0
                continue
            dR_full = grads["dR"][l_idx]
            g_theta = np.array([float(np.sum(dR_full * E)) for E in E_list])
            thetas[l_idx] = thetas[l_idx]  # (theta itself updated via Adam below on projected dR)
            dR_proj = sum(g_theta[k] * E_list[k] for k in range(len(E_list)))
            grads["dR"][l_idx][:] = dR_proj

        g = b18.flatten_grad(params, grads)
        flat, m_, v_ = b18.adam_step(flat, m_, v_, g, step, lr)
        b18.unflatten_into(params, flat)
        b18.project_stable(params)
        flat = b18.flatten_params(params)
        losses.append(loss)
        if not np.isfinite(loss):
            break
    median_late = float(np.median(losses[-50:])) if len(losses) >= 50 else \
        (float(np.median(losses)) if losses else None)
    return dict(median_late_loss=median_late,
               final_loss=float(losses[-1]) if losses else None, losses=losses)


def two_layer_specs(arch_name, r, seed, family_for_dense="dense"):
    """Build a 2-layer constrained-training spec list, both layers using
    the same architecture family (dense / commuting / polynomial /
    single-generic-tangent / single-commuting-tangent)."""
    rng = np.random.RandomState(seed)
    specs = []
    for _ in range(2):
        if arch_name == "dense":
            R, E = arch_dense(r, rng)
        elif arch_name == "commuting":
            R, E = arch_commuting_diag(r, rng)
        elif arch_name == "polynomial":
            R, E = arch_polynomial(r, min(4, r), rng)
        elif arch_name == "single_generic":
            R, E = arch_single_tangent(r, rng, "generic")
        elif arch_name == "single_commuting":
            R0, E_all = arch_commuting_diag(r, rng)
            R, E = R0, [E_all[0]]  # a single one of the commuting directions
        else:
            raise ValueError(arch_name)
        specs.append(dict(width=r, r=r, R_fixed=R, E_list=E, routing="dense"))
    return specs


# ---------------------------------------------------------------------------
# Part E: known-order teacher test. Teacher = K independent stable
# exponential modes (order K exactly known); does r_req track K, and does
# increasing multiplicity n fail to repair a too-small r?
# ---------------------------------------------------------------------------
def make_k_mode_teacher_task(rng, T_, BATCH_, M_IN_, arg):
    K, mus = arg
    x = rng.randn(T_, BATCH_, 1)
    s = np.zeros((K, BATCH_))
    y = np.zeros((T_, BATCH_))
    for t in range(T_):
        s = mus[:, None] * s + x[t, :, 0][None, :]
        y[t] = s.mean(axis=0)
    return x, y


# ---------------------------------------------------------------------------
# Part G: selectivity algebra. Extends B18 Part G: G1 commuting selector
# family (R(q) = R0 + q*Delta, Delta IN the commutant of R0 -- credit
# should stay O(dim A)); G2 noncommuting selector generator confined to
# the shared core (Delta generic, not commuting -- credit may grow toward
# r^2 but should stay INDEPENDENT of n); G3 unrestricted (reproduces B17/
# B18's wide-state blowup, not retested here -- see those phases).
# ---------------------------------------------------------------------------
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))


def dsigmoid(z):
    s = sigmoid(z)
    return s * (1 - s)


def part_g_selectivity_algebra(n_list, r=4, N0=8, T_=30, seed=0, c_gate=1.0,
                               selector_kind="commuting"):
    rng = np.random.RandomState(seed)
    results = []
    R0 = arch_commuting_diag(r, rng)[0] * 0.85
    if selector_kind == "commuting":
        Delta = arch_commuting_diag(r, rng)[1][0]  # one commuting direction
    elif selector_kind == "noncommuting":
        Delta = rng.randn(r, r)
    else:
        raise ValueError(selector_kind)

    for n in n_list:
        N1 = n * r
        u = rng.randn(T_, N0)
        B = rng.randn(N1, N0) / np.sqrt(N0)
        theta0 = np.ones(N0)
        a0 = 0.85

        def R_of(q):
            return R0 + q * Delta

        def simulate(theta, gate_kind):
            h0 = np.zeros(N0); h1 = np.zeros((n, r))
            for t in range(T_):
                h0 = a0 * h0 + theta * u[t]
                if gate_kind == "G1_nonselective":
                    R_t = R0
                elif gate_kind == "G2_exogenous":
                    R_t = R_of(c_gate * np.sin(0.3 * t))
                else:  # G3_endogenous
                    R_t = R_of(c_gate * np.mean(h0))
                Bh0 = (B @ h0).reshape(n, r)
                h1 = h1 @ R_t.T + Bh0
            return h1.reshape(-1)

        eps = 1e-5
        for gate_kind in ("G1_nonselective", "G2_exogenous", "G3_endogenous"):
            J_fd = np.zeros((N1, N0))
            for m in range(N0):
                tp = theta0.copy(); tp[m] += eps
                tm = theta0.copy(); tm[m] -= eps
                J_fd[:, m] = (simulate(tp, gate_kind) - simulate(tm, gate_kind)) / (2 * eps)

            h0 = np.zeros(N0)
            R_t_seq, h0_seq = [], []
            for t in range(T_):
                h0 = a0 * h0 + theta0 * u[t]
                if gate_kind == "G1_nonselective":
                    R_t = R0
                elif gate_kind == "G2_exogenous":
                    R_t = R_of(c_gate * np.sin(0.3 * t))
                else:
                    R_t = R_of(c_gate * np.mean(h0))
                R_t_seq.append(R_t); h0_seq.append(h0.copy())
            h1_true = np.zeros((n, r)); h1_traj = []
            for t in range(T_):
                Bh0 = (B @ h0_seq[t]).reshape(n, r)
                h1_true = h1_true @ R_t_seq[t].T + Bh0
                h1_traj.append(h1_true.copy())
            h1_prev_traj = [np.zeros((n, r))] + h1_traj[:-1]

            J_corrected = np.zeros((N1, N0))
            for m in range(N0):
                z = 0.0; W = B[:, m].reshape(n, r); s = np.zeros((n, r))
                for t in range(T_):
                    z = a0 * z + u[t, m]
                    if gate_kind == "G3_endogenous":
                        extra = (h1_prev_traj[t] @ Delta.T) * (c_gate / N0 * z)
                    else:
                        extra = 0.0
                    s = s @ R_t_seq[t].T + extra + W * z
                J_corrected[:, m] = s.reshape(-1)

            scale = float(np.max(np.abs(J_fd)) + 1e-30)
            gap_corr = float(np.max(np.abs(J_fd - J_corrected)))
            # measured rank of the correction term's own spatial trajectory
            traj_mat = np.stack(h1_prev_traj, axis=0).reshape(T_, -1)
            sv = np.linalg.svd(traj_mat, compute_uv=False)
            traj_rank = int(np.sum(sv > 1e-9 * sv[0])) if len(sv) and sv[0] > 0 else 0
            results.append(dict(selector_kind=selector_kind, n=n, N1=N1, gate=gate_kind,
                                gap_corrected_rel=gap_corr / scale, h1_traj_rank=traj_rank))
    return results
