"""Phase B34a -- nonlinear truncated-polynomial / jet-algebra exact RTRL.
Actual trainable nonlinear recurrent model where P=r, ALL r trainable
parameter directions affect the recurrent transformation, rank(D_theta
h_t)=r generically, yet exact persistent eligibility needs only r
dynamic scalars (not r^2).

Algebra: A_r = R[eps]/(eps^r), elements = length-r coefficient vectors
u=(u_0,...,u_{r-1}). Multiplication = truncated convolution:
(u*v)_k = sum_{i=0}^k u_i v_{k-i}. Direct float64 implementation (NOT
FFT) via the exact lower-triangular Toeplitz regular-representation
matrix M_u (M_u)_{k,i}=u_{k-i} for k>=i else 0 -- M_u @ M_v = M_{u*v}
exactly (standard fact for the regular rep of a commutative ring),
which is what lets S_t stay of the form M_{s_t} for all t.

Model (theta in A_r trainable; a_t,b_t,kappa_t,c_t in A_r exogenous,
causal, generated by a FIXED FROZEN function of an external input,
independent of theta and h):
  y_t = (a_t + kappa_t*theta)*h_t + b_t*theta + c_t
  phi(y) = c_1 y + c_3 y^{*3}      (polynomial nonlinearity, algebra powers)
  h_{t+1} = phi(y_t)
  d_t = phi'(y_t) = c_1*1 + 3 c_3 y_t^{*2}     (1 = (1,0,...,0))

Theory (verified here against independent autodiff, not merely
asserted): J_t = M_{d_t*(a_t+kappa_t*theta)}, G_t = M_{d_t*(kappa_t*h_t+b_t)}.
Reduced eligibility s_t in R^r:
  s_{t+1} = d_t*[(a_t+kappa_t*theta)*s_t + kappa_t*h_t + b_t]

Run: python -m credit_memory.b34a_jet_algebra_correctness
"""
from __future__ import annotations

import numpy as np
import jax
import jax.numpy as jnp
from jax.flatten_util import ravel_pytree

jax.config.update("jax_enable_x64", True)

X_DIM = 4
GEN_HIDDEN = 24
C1 = 1.0
C3 = 0.05


# ---------------------------------------------------------------------
# Algebra primitives -- direct float64 truncated convolution, NOT FFT.
# ---------------------------------------------------------------------
def make_M(u, r):
    """Exact lower-triangular Toeplitz regular-representation matrix:
    (M_u)_{k,i} = u_{k-i} for k>=i, else 0."""
    idx = jnp.arange(r)
    diff = idx[:, None] - idx[None, :]
    mask = diff >= 0
    safe_diff = jnp.where(mask, diff, 0)
    return jnp.where(mask, u[safe_diff], 0.0)


def alg_mult(u, v, r):
    return make_M(u, r) @ v


def alg_one(r):
    return jnp.eye(r)[0]


def transpose_mult(u, q, r):
    """M_u^T @ q via the DIRECT truncated-correlation formula, WITHOUT
    ever materializing M_u. (M_u^T @ q)_p = sum_{j=0}^{r-1-p} u_j q_{p+j}."""
    out = []
    for p in range(r):
        out.append(jnp.dot(u[: r - p], q[p:r]))
    return jnp.stack(out)


# ---------------------------------------------------------------------
# Fixed, FROZEN (never trained) exogenous coefficient generator.
# ---------------------------------------------------------------------
def make_gen_params(seed, r):
    rng = np.random.RandomState(seed)
    scale1 = 1.0 / np.sqrt(X_DIM)
    scale2 = 1.0 / np.sqrt(GEN_HIDDEN)
    return dict(
        W1=jnp.array(rng.randn(GEN_HIDDEN, X_DIM) * scale1),
        b1=jnp.array(rng.randn(GEN_HIDDEN) * 0.1),
        W_a=jnp.array(rng.randn(r, GEN_HIDDEN) * scale2),
        b_a=jnp.array(rng.randn(r) * 0.05),
        W_b=jnp.array(rng.randn(r, GEN_HIDDEN) * scale2),
        b_b=jnp.array(rng.randn(r) * 0.05),
        W_k=jnp.array(rng.randn(r, GEN_HIDDEN) * scale2),
        b_k=jnp.array(rng.randn(r) * 0.05),
        W_c=jnp.array(rng.randn(r, GEN_HIDDEN) * scale2),
        b_c=jnp.array(rng.randn(r) * 0.05),
    )


def gen_forward(x_t, gen_params, r):
    hid = jnp.tanh(gen_params["W1"] @ x_t + gen_params["b1"])
    a_t = 0.25 * jnp.tanh(gen_params["W_a"] @ hid + gen_params["b_a"])
    b_t = 0.1 * jnp.tanh(gen_params["W_b"] @ hid + gen_params["b_b"])
    c_t = 0.1 * jnp.tanh(gen_params["W_c"] @ hid + gen_params["b_c"])
    k_raw = gen_params["W_k"] @ hid + gen_params["b_k"]
    kappa_t = 0.1 * jnp.tanh(k_raw)
    # kappa_t[0] forced to a UNIT-guaranteed range [0.2,0.8] -- an
    # element of A_r is invertible iff its constant term is nonzero
    # (A_r is local with maximal ideal (eps)); this is the precise
    # condition used for the "kappa_t sufficiently invertible" diagnostic.
    kappa0 = 0.5 + 0.3 * jnp.tanh(k_raw[0])
    kappa_t = kappa_t.at[0].set(kappa0)
    return a_t, b_t, kappa_t, c_t


# ---------------------------------------------------------------------
# Model forward step.
# ---------------------------------------------------------------------
def phi(y, r):
    y2 = alg_mult(y, y, r)
    y3 = alg_mult(y2, y, r)
    return C1 * y + C3 * y3


def phi_prime(y, r):
    y2 = alg_mult(y, y, r)
    return C1 * alg_one(r) + 3.0 * C3 * y2


def h_step(h, theta, x_t, gen_params, r, eps=0.0, R_mat=None):
    a_t, b_t, kappa_t, c_t = gen_forward(x_t, gen_params, r)
    A_theta_t = a_t + alg_mult(kappa_t, theta, r)
    y_t = alg_mult(A_theta_t, h, r) + alg_mult(b_t, theta, r) + c_t
    h_next = phi(y_t, r)
    if R_mat is not None:
        h_next = h_next + eps * (R_mat @ h)
    return h_next


def rollout_h(h0, theta, xs, gen_params, r, eps=0.0, R_mat=None):
    def step(h, x_t):
        h_next = h_step(h, theta, x_t, gen_params, r, eps, R_mat)
        return h_next, h_next
    _, Hs = jax.lax.scan(step, h0, xs)
    return Hs


def ell(y, phase):
    return jnp.sin(y + phase) + 0.5 * y ** 2


def dell_dy(y, phase):
    return jnp.cos(y + phase) + y


def loss_bptt(theta, h0, xs, qs, phases, gen_params, r, eps, R_mat):
    Hs = rollout_h(h0, theta, xs, gen_params, r, eps, R_mat)
    ys = jnp.einsum("ti,ti->t", Hs, qs)
    return jnp.sum(ell(ys, phases))


def make_grad_bptt_fn():
    return jax.jit(jax.grad(loss_bptt, argnums=0), static_argnums=(6,))


def full_rtrl_grad(theta, h0, xs, qs, phases, gen_params, r, eps=0.0, R_mat=None):
    T = xs.shape[0]
    h = h0
    S = jnp.zeros((r, r), dtype=jnp.float64)
    g_total = jnp.zeros(r, dtype=jnp.float64)
    S_traj = []
    for t in range(T):
        x_t = xs[t]
        J_t = jax.jacobian(lambda hh: h_step(hh, theta, x_t, gen_params, r, eps, R_mat))(h)
        G_t = jax.jacobian(lambda th: h_step(h, th, x_t, gen_params, r, eps, R_mat))(theta)
        S = J_t @ S + G_t
        S_traj.append(S)
        h_next = h_step(h, theta, x_t, gen_params, r, eps, R_mat)
        y = qs[t] @ h_next
        dl_dh = dell_dy(y, phases[t]) * qs[t]
        g_total = g_total + dl_dh @ S
        h = h_next
    return g_total, jnp.stack(S_traj)


def reduced_algebra_grad(theta, h0, xs, qs, phases, gen_params, r):
    """Reduced algebra eligibility: s_t in R^r. Gradient contraction
    uses the DIRECT transpose-correlation action, never materializing
    M_{s_t}."""
    T = xs.shape[0]
    h = h0
    s = jnp.zeros(r, dtype=jnp.float64)
    g_total = jnp.zeros(r, dtype=jnp.float64)
    s_traj = []
    for t in range(T):
        x_t = xs[t]
        a_t, b_t, kappa_t, c_t = gen_forward(x_t, gen_params, r)
        A_theta_t = a_t + alg_mult(kappa_t, theta, r)
        y_t = alg_mult(A_theta_t, h, r) + alg_mult(b_t, theta, r) + c_t
        d_t = phi_prime(y_t, r)
        inner = alg_mult(A_theta_t, s, r) + alg_mult(kappa_t, h, r) + b_t
        s = alg_mult(d_t, inner, r)
        s_traj.append(s)
        h_next = phi(y_t, r)
        y = qs[t] @ h_next
        dl_dh = dell_dy(y, phases[t]) * qs[t]
        g_total = g_total + transpose_mult(s, dl_dh, r)
        h = h_next
    return g_total, jnp.stack(s_traj)


def reconstruct_S(s_traj, r):
    T = s_traj.shape[0]
    return jnp.stack([make_M(s_traj[t], r) for t in range(T)])


def make_setting(seed, T, r):
    rng = np.random.RandomState(seed)
    theta = jnp.array(rng.randn(r) * 0.2)
    h0 = jnp.array(rng.randn(r) * 0.15)
    xs = jnp.array(rng.randn(T, X_DIM) * 0.6)
    qs = jnp.array(rng.randn(T, r))
    phases = jnp.array(rng.uniform(0, 2 * np.pi, size=T))
    return theta, h0, xs, qs, phases


def run_correctness_suite(r, seeds=(0, 1, 2, 3, 4), lengths=(1, 5, 20, 100, 500)):
    print("=" * 78)
    print(f"B34a correctness suite: r=P={r}, jet algebra R[eps]/(eps^{r})")
    print("=" * 78)
    gen_params = make_gen_params(seed=1000 + r, r=r)
    grad_bptt_fn = make_grad_bptt_fn()
    eps_num = 1e-12
    worst = dict(full=0.0, reduced=0.0, S_recon=0.0)
    rank_fracs = []
    exact_rank_fracs = []
    cond_numbers = []
    s0_magnitudes = []
    max_h_seen = 0.0

    for T in lengths:
        for seed in seeds:
            theta, h0, xs, qs, phases = make_setting(seed, T, r)
            g_b = grad_bptt_fn(theta, h0, xs, qs, phases, gen_params, r, 0.0, None)
            g_f, S_traj = full_rtrl_grad(theta, h0, xs, qs, phases, gen_params, r)
            g_r, s_traj = reduced_algebra_grad(theta, h0, xs, qs, phases, gen_params, r)

            rel_full = float(jnp.linalg.norm(g_f - g_b) / (jnp.linalg.norm(g_b) + eps_num))
            rel_reduced = float(jnp.linalg.norm(g_r - g_b) / (jnp.linalg.norm(g_b) + eps_num))

            S_np = np.asarray(S_traj)
            S_hat = np.asarray(reconstruct_S(s_traj, r))
            recon_err = float(np.max(np.abs(S_np - S_hat)))

            worst["full"] = max(worst["full"], rel_full)
            worst["reduced"] = max(worst["reduced"], rel_reduced)
            worst["S_recon"] = max(worst["S_recon"], recon_err)

            Hs = np.asarray(rollout_h(h0, theta, xs, gen_params, r))
            max_h_seen = max(max_h_seen, float(np.max(np.abs(Hs))))

            rank_idx = list(range(min(T, 20))) if T <= 200 else list(range(0, T, max(1, T // 20)))
            ranks = []
            exact_ranks = []
            for t_idx in rank_idx:
                M = S_np[t_idx]
                sv = np.linalg.svd(M, compute_uv=False)
                ranks.append(int(np.sum(sv > 1e-9 * sv[0])) if sv[0] > 1e-12 else 0)
                # EXACT structural criterion: M is lower-triangular Toeplitz
                # with CONSTANT diagonal = s_t[0] (the algebra element's own
                # constant term), so det(M)=s_t[0]^r exactly, and M is full
                # rank iff s_t[0] != 0 -- this is the mathematically correct
                # rank test for this specific structure (a naive SVD/sv>tol
                # threshold becomes numerically unreliable at large r because
                # M is a highly ill-conditioned nilpotent+scalar Jordan-like
                # matrix: det=s_t[0]^r can be astronomically small in
                # magnitude even though s_t[0] itself is clearly nonzero).
                s0 = float(np.diag(M)[0])
                exact_ranks.append(r if abs(s0) > 1e-6 else 0)
                cond_numbers.append(float(sv[0] / sv[-1]) if sv[-1] > 0 else float("inf"))
                s0_magnitudes.append(abs(s0))
            frac_full = float(np.mean([rk == r for rk in ranks])) if ranks else float("nan")
            frac_exact = float(np.mean([rk == r for rk in exact_ranks])) if exact_ranks else float("nan")
            rank_fracs.append(frac_full)
            exact_rank_fracs.append(frac_exact)

            print(f"  T={T:4d} seed={seed}  full_rel={rel_full:.3e}  reduced_rel={rel_reduced:.3e}  "
                  f"S_recon max|d|={recon_err:.3e}  SVD_frac_rank{r}(sampled)={frac_full:.2f}  "
                  f"EXACT_frac_rank{r}(sampled)={frac_exact:.2f}")

    print("-" * 78)
    print(f"WORST: full_rel={worst['full']:.3e}  reduced_rel={worst['reduced']:.3e}  "
          f"S_recon={worst['S_recon']:.3e}")
    print(f"Mean SVD-based frac_rank{r} across all settings: {np.mean(rank_fracs):.4f}")
    print(f"Mean EXACT (diagonal-criterion) frac_rank{r} across all settings: {np.mean(exact_rank_fracs):.4f}")
    print(f"Median condition number of sampled S_t: {np.median(cond_numbers):.3e}  "
          f"(min diag |s_t[0]| sampled: {np.min(s0_magnitudes):.3e})")
    print(f"Max |h_t| observed across all settings: {max_h_seen:.4f} (stability check)")
    all_pass = all(v_ < 1e-8 for v_ in worst.values())
    print(f"ALL < 1e-8: {all_pass}")
    return dict(all_pass=all_pass, worst=worst, mean_rank_frac=float(np.mean(rank_fracs)),
                mean_exact_rank_frac=float(np.mean(exact_rank_fracs)),
                median_cond=float(np.median(cond_numbers)), min_s0=float(np.min(s0_magnitudes)),
                gen_params=gen_params, max_h_seen=max_h_seen)


if __name__ == "__main__":
    for r in (4, 16, 64):
        run_correctness_suite(r)
        print()
